### ISSUE TITLE
ideas for new ini reader

### ISSUE THREAD

**Issue by ThirteenAG** [ThirteenAG/IniReader#2]
Currently there's mixed usage of winapi and other things, comments weren't saved until recently, when writing ini and other issues.

Public api includes:

```
CompareBySections
CompareByValues
GetIniPath
SetIniPath
SetIniPath
ReadInteger
ReadFloat
ReadBoolean
ReadString
WriteInteger
WriteFloat
WriteBoolean
WriteString
```

I think it's worth making a more flexible ini reader/writer, and add more neat features, something like 

```
ReadList
ReadJson
ReadSection
ForEachValueInSection
```
etc...

Make sure paths and symbols are parsed correctly, make tests and add ci.
I'll make a more specific list later.

**Comment by xan1242** [comment]
I mean if you're gonna add json parsing, that should be its own thing. Mixing and matching ini and json sounds like a bad idea lol

Json can do everything ini does (probably even better).

Maybe for single line jsons (that is stored in an ini) it could be good but then again, you're better off saving it into its own file imo

Ini files are very dumb and simple by design. I'm actually not sure what you could improve upon here in practice other than making a cross-platform implementation (which was already done in other projects).

Things like [mINI](https://github.com/pulzed/mINI) already offer iterators for sections which you could wrap around and make a comparator for.

**Comment by ThirteenAG** [comment]
Yeah, I realize that, maybe it's not gonna happen. It's just some ideas I have, nothing concrete.
